from __future__ import annotations

import json
import os
import re
from typing import Any

from automation.listening.config import (
    CORE_SENTENCE_COUNT,
    FEW_SHOT_DIR,
    SUMMARY_PART_COUNT,
    WORDCARD_COUNT,
    allow_openai_fallback,
    openai_configured,
)
from automation.listening.models import Segment, VideoMeta
from automation.listening.script.canonical import group_paragraphs
from automation.listening.utils import segment_hash, split_sentences
from automation.listening.vertex_client import (
    LITERAL_KR_INSTRUCTION,
    generate_json,
    translate_literal_kr,
    vertex_configured,
)


def build_04_en_manifest(segments: list[Segment]) -> list[dict[str, str]]:
    return [{"segment_id": s.segment_id, "hash": segment_hash(s.text_en)} for s in segments]


def assemble_04_en(segments: list[Segment]) -> tuple[str, list[dict[str, str]]]:
    paragraphs = group_paragraphs(segments)
    manifest = build_04_en_manifest(segments)
    lines: list[str] = []
    for i, para in enumerate(paragraphs, start=1):
        lines.append(f"[Paragraph {i}]")
        lines.append(f"EN: {para}")
        lines.append("KR: ")
    return "\n".join(lines).rstrip() + "\n", manifest


def verify_04_en_manifest(segments: list[Segment], content_04: str, manifest: list[dict[str, str]] | None = None) -> bool:
    manifest = manifest or build_04_en_manifest(segments)
    if len(manifest) != len(segments):
        return False
    en_blob = "\n".join(
        line[3:].strip()
        for line in content_04.splitlines()
        if line.strip().upper().startswith("EN:")
    )
    normalized_blob = re.sub(r"\s+", " ", en_blob).strip().lower()
    for entry, seg in zip(manifest, segments):
        expected = entry.get("hash") or segment_hash(seg.text_en)
        actual = segment_hash(seg.text_en)
        if expected != actual:
            return False
        needle = re.sub(r"\s+", " ", seg.text_en).strip().lower()
        if needle and needle not in normalized_blob:
            return False
    return len(manifest) > 0


def inject_kr_into_04(en_content: str, kr_paragraphs: list[str]) -> str:
    lines = en_content.splitlines()
    out: list[str] = []
    kr_idx = 0
    for line in lines:
        if line.strip().upper().startswith("KR:") and kr_idx < len(kr_paragraphs):
            out.append(f"KR: {kr_paragraphs[kr_idx]}")
            kr_idx += 1
        else:
            out.append(line)
    return "\n".join(out) + "\n"


def generate_meta(meta: VideoMeta, level: int) -> str:
    return (
        f"title: {meta.title}\n"
        f"level: Level {level}\n"
        f"source: YouTube\n"
        f"video_url: {meta.video_url}\n"
        f"video_id: {meta.video_id}\n"
        f"channel: {meta.channel or '-'}\n"
        f"notes: auto-generated by listening automation v1\n"
    )


def _transcript_text(segments: list[Segment]) -> str:
    return " ".join(s.text_en for s in segments)


def _all_sentences(segments: list[Segment]) -> list[str]:
    sents: list[str] = []
    for seg in segments:
        sents.extend(split_sentences(seg.text_en))
    return sents


def _few_shot(name: str, max_lines: int = 35) -> str:
    path = FEW_SHOT_DIR / name
    if not path.exists():
        return ""
    return "\n".join(path.read_text(encoding="utf-8").splitlines()[:max_lines])


def _translate(en: str, *, allow_placeholder: bool = False) -> str:
    if vertex_configured():
        try:
            return translate_literal_kr(en)
        except Exception as exc:
            if not allow_placeholder:
                raise RuntimeError(f"BLOCKED: literal KR translation failed: {exc}") from exc
    if openai_configured():
        try:
            return _openai_literal(en)
        except Exception as exc:
            if not allow_placeholder:
                raise RuntimeError(f"BLOCKED: OpenAI fallback failed: {exc}") from exc
    if allow_placeholder:
        return f"[KR translation pending: {en[:60]}...]"
    raise RuntimeError("BLOCKED: Vertex AI (ADC) required for literal KR translation")


def generate_intro_from_transcript(segments: list[Segment], *, allow_placeholder: bool = False) -> str:
    transcript = _transcript_text(segments)
    if vertex_configured() and not allow_placeholder:
        example = _few_shot("01_intro.txt", 5)
        data = generate_json(
            f"""Create one intro for an English listening lesson page.
Example:
{example}

Write one EN intro sentence (1-2 sentences) summarizing the story for learners.
Use content from this transcript only. Return JSON: {{"intro_en": "..."}}

Transcript excerpt:
{transcript[:8000]}
"""
        )
        en = str(data.get("intro_en", "")).strip()
    else:
        sents = _all_sentences(segments)
        en = sents[0] if sents else transcript[:200]

    kr = _translate(en, allow_placeholder=allow_placeholder)
    return f"EN: {en}\nKR: {kr}\n"


def generate_core_from_transcript(segments: list[Segment], *, allow_placeholder: bool = False) -> str:
    all_sents = _all_sentences(segments)
    if len(all_sents) < CORE_SENTENCE_COUNT:
        raise RuntimeError(f"BLOCKED: transcript has fewer than {CORE_SENTENCE_COUNT} sentences for Core")

    if vertex_configured() and not allow_placeholder:
        example = _few_shot("02_core.txt", 24)
        transcript = _transcript_text(segments)
        data = generate_json(
            f"""Select exactly {CORE_SENTENCE_COUNT} key sentences from the transcript for Core Sentences.
Rules:
- Use complete sentences verbatim from the transcript (no rewriting)
- Spread across beginning, middle, and end
- Return JSON: {{"sentences": ["...", ...]}} with exactly {CORE_SENTENCE_COUNT} strings

Example format:
{example}

Transcript:
{transcript[:14000]}
"""
        )
        picked = [str(s).strip() for s in data.get("sentences", []) if str(s).strip()]
        if len(picked) != CORE_SENTENCE_COUNT:
            raise RuntimeError(f"BLOCKED: Core generation returned {len(picked)} sentences, need {CORE_SENTENCE_COUNT}")
    else:
        picked = _pick_evenly(all_sents, CORE_SENTENCE_COUNT)

    lines: list[str] = []
    for i, sent in enumerate(picked, start=1):
        kr = _translate(sent, allow_placeholder=allow_placeholder)
        lines.append(f"[Sentence {i}]")
        lines.append(f"EN: {sent}")
        lines.append(f"KR: {kr}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def generate_summary_from_transcript(segments: list[Segment], *, allow_placeholder: bool = False) -> str:
    transcript = _transcript_text(segments)
    if vertex_configured() and not allow_placeholder:
        example = _few_shot("03_summary.txt", 20)
        data = generate_json(
            f"""Create exactly {SUMMARY_PART_COUNT} summary parts for an English listening lesson.
Each part: one EN sentence summarizing a story section (concise but complete).
Then KR will be literal translation separately.

Example:
{example}

Return JSON: {{"parts": ["EN sentence 1", ...]}} with exactly {SUMMARY_PART_COUNT} strings.

Transcript:
{transcript[:14000]}
"""
        )
        parts = [str(p).strip() for p in data.get("parts", []) if str(p).strip()]
        if len(parts) != SUMMARY_PART_COUNT:
            raise RuntimeError(f"BLOCKED: Summary generation returned {len(parts)} parts, need {SUMMARY_PART_COUNT}")
    else:
        sents = _all_sentences(segments)
        parts = _pick_evenly(sents, SUMMARY_PART_COUNT)

    lines: list[str] = []
    for i, en in enumerate(parts, start=1):
        kr = _translate(en, allow_placeholder=allow_placeholder)
        lines.append(f"[Part {i}]")
        lines.append(f"EN: {en}")
        lines.append(f"KR: {kr}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def generate_wordcards_from_transcript(
    segments: list[Segment],
    core_text: str,
    *,
    allow_placeholder: bool = False,
) -> str:
    transcript = _transcript_text(segments)
    if vertex_configured() and not allow_placeholder:
        example = _few_shot("05_wordcard.txt", 45)
        data = generate_json(
            f"""Create exactly {WORDCARD_COUNT} vocabulary word cards from this English listening story.
Each card must have: headword, part_of_speech, meaning_kr, definition_en, definition_kr_literal, example_en, example_kr_literal.
Pick words useful for learners; examples must come from or relate to the story.

Example:
{example}

Return JSON array of {WORDCARD_COUNT} objects with those keys.

Transcript excerpt:
{transcript[:10000]}

Core sentences excerpt:
{core_text[:3000]}
"""
        )
        cards = data if isinstance(data, list) else data.get("cards", [])
        if len(cards) != WORDCARD_COUNT:
            raise RuntimeError(f"BLOCKED: Word card generation returned {len(cards)} cards, need {WORDCARD_COUNT}")
    else:
        cards = _heuristic_wordcards(core_text)

    lines: list[str] = []
    for i, card in enumerate(cards, start=1):
        hw = card.get("headword", "word")
        lines.append(f"[Card {i}]")
        lines.append(f"headword: {hw}")
        lines.append(f"part_of_speech: {card.get('part_of_speech', 'noun')}")
        meaning = card.get("meaning_kr") or _translate(hw, allow_placeholder=allow_placeholder)
        lines.append(f"meaning_kr: {meaning}")
        lines.append(f"definition_en: {card.get('definition_en', f'definition of {hw}')}")
        def_kr = card.get("definition_kr_literal") or _translate(
            str(card.get("definition_en", hw)), allow_placeholder=allow_placeholder
        )
        lines.append(f"definition_kr_literal: {def_kr}")
        ex_en = card.get("example_en", f"This story mentions {hw}.")
        lines.append(f"example_en: {ex_en}")
        ex_kr = card.get("example_kr_literal") or _translate(ex_en, allow_placeholder=allow_placeholder)
        lines.append(f"example_kr_literal: {ex_kr}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def translate_paragraphs_kr(paragraphs: list[str], *, allow_placeholder: bool = False) -> list[str]:
    instruction = (
        f"{LITERAL_KR_INSTRUCTION}\n"
        "The English paragraph must map one-to-one to Korean. "
        "Do not merge, split, omit, or add sentences."
    )
    return [
        _translate_with_instruction(p, instruction, allow_placeholder=allow_placeholder) for p in paragraphs
    ]


def _translate_with_instruction(en: str, instruction: str, *, allow_placeholder: bool = False) -> str:
    if vertex_configured():
        try:
            from automation.listening.vertex_client import generate_text

            return generate_text(f"{instruction}\n\nEnglish:\n{en}")
        except Exception as exc:
            if not allow_placeholder:
                raise RuntimeError(f"BLOCKED: 04 KR literal translation failed: {exc}") from exc
    if openai_configured():
        try:
            return _openai_literal(en, instruction)
        except Exception as exc:
            if not allow_placeholder:
                raise RuntimeError(f"BLOCKED: OpenAI fallback failed: {exc}") from exc
    if allow_placeholder:
        return f"[KR translation pending: {en[:60]}...]"
    raise RuntimeError("BLOCKED: Vertex AI (ADC) required for 04 KR translation")


def _heuristic_wordcards(core_text: str) -> list[dict[str, Any]]:
    words = re.findall(r"\b[A-Za-z]{4,}\b", core_text)
    unique: list[str] = []
    for w in words:
        lw = w.lower()
        if lw not in unique:
            unique.append(lw)
        if len(unique) >= WORDCARD_COUNT:
            break
    while len(unique) < WORDCARD_COUNT:
        unique.append(f"word{len(unique)+1}")
    return [
        {
            "headword": w,
            "part_of_speech": "noun",
            "definition_en": f"common English definition of {w}",
            "example_en": f"This story mentions {w} in an important moment.",
        }
        for w in unique[:WORDCARD_COUNT]
    ]


def _pick_evenly(items: list[str], count: int) -> list[str]:
    if len(items) < count:
        return items
    step = len(items) / count
    return [items[int(i * step)] for i in range(count)]


def _openai_literal(en: str, instruction: str | None = None) -> str:
    if not allow_openai_fallback():
        raise RuntimeError("BLOCKED: OpenAI fallback not allowed (set ALLOW_OPENAI_FALLBACK=1)")
    from openai import OpenAI

    prompt = instruction or LITERAL_KR_INSTRUCTION
    client = OpenAI()
    resp = client.chat.completions.create(
        model=os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        messages=[{"role": "user", "content": f"{prompt}\n\nEnglish:\n{en}"}],
    )
    return (resp.choices[0].message.content or "").strip()


def _count_blocks(content: str, label: str) -> int:
    return len(re.findall(rf"\[{re.escape(label)}\s+\d+\]", content))


def validate_format_files(files: dict[str, str], *, reject_placeholders: bool = True) -> tuple[bool, str]:
    required = {
        "00_meta.txt": ["title:", "level:"],
        "01_intro.txt": ["EN:", "KR:"],
        "02_core.txt": ["[Sentence"],
        "03_summary.txt": ["[Part"],
        "04_full_script.txt": ["[Paragraph", "EN:"],
        "05_wordcard.txt": ["[Card"],
    }
    for name, markers in required.items():
        content = files.get(name, "")
        for m in markers:
            if m not in content:
                return False, f"{name} missing {m}"
        if reject_placeholders and "[KR translation pending:" in content:
            return False, f"{name} contains untranslated placeholder KR"

    core_n = _count_blocks(files.get("02_core.txt", ""), "Sentence")
    if core_n != CORE_SENTENCE_COUNT:
        return False, f"02_core.txt has {core_n} sentences, need {CORE_SENTENCE_COUNT}"
    sum_n = _count_blocks(files.get("03_summary.txt", ""), "Part")
    if sum_n != SUMMARY_PART_COUNT:
        return False, f"03_summary.txt has {sum_n} parts, need {SUMMARY_PART_COUNT}"
    card_n = _count_blocks(files.get("05_wordcard.txt", ""), "Card")
    if card_n != WORDCARD_COUNT:
        return False, f"05_wordcard.txt has {card_n} cards, need {WORDCARD_COUNT}"

    return True, "OK"
