from __future__ import annotations

import json
import os
import re
from typing import Any

from automation.listening.config import (
    FEW_SHOT_DIR,
    LEVEL_GENERATION_GUIDANCE,
    LISTENING_ROOT,
    WORDCARD_MAX,
    WORDCARD_MIN,
    allow_openai_fallback,
    level_folder,
    openai_configured,
)
from automation.listening.generate.sections import (
    build_story_sections,
    extract_core_sentences,
    fill_section_content,
    render_core_file,
    render_summary_file,
)
from automation.listening.models import Segment, StorySection, VideoMeta
from automation.listening.script.canonical import group_paragraphs
from automation.listening.script.caption_restore import is_complete_sentence
from automation.listening.utils import normalize_text, segment_hash, split_sentences
from automation.listening.vertex_client import (
    LITERAL_KR_INSTRUCTION,
    generate_json,
    meaning_conflicts_with_context,
    translate_literal_kr,
    translate_literal_kr_batch,
    vertex_configured,
)

WORDCARD_FIELDS = (
    "headword:",
    "part_of_speech:",
    "meaning_kr:",
    "definition_en:",
    "definition_kr_literal:",
    "example_en:",
    "example_kr_literal:",
)


def build_04_en_manifest(segments: list[Segment]) -> list[dict[str, str]]:
    return [{"segment_id": s.segment_id, "hash": segment_hash(s.text_en)} for s in segments]


def assemble_04_en(segments: list[Segment]) -> tuple[str, list[dict[str, str]]]:
    paragraphs = group_paragraphs(segments)
    manifest = build_04_en_manifest(segments)
    lines: list[str] = []
    for i, para in enumerate(paragraphs, start=1):
        lines.append(f"[Paragraph {i}]")
        lines.append(f"EN: {para}")
        lines.append("KR: ")
    return "\n".join(lines).rstrip() + "\n", manifest


def verify_04_en_manifest(segments: list[Segment], content_04: str, manifest: list[dict[str, str]] | None = None) -> bool:
    manifest = manifest or build_04_en_manifest(segments)
    if len(manifest) != len(segments):
        return False
    en_blob = "\n".join(
        line[3:].strip()
        for line in content_04.splitlines()
        if line.strip().upper().startswith("EN:")
    )
    normalized_blob = re.sub(r"\s+", " ", en_blob).strip().lower()
    for entry, seg in zip(manifest, segments):
        expected = entry.get("hash") or segment_hash(seg.text_en)
        actual = segment_hash(seg.text_en)
        if expected != actual:
            return False
        needle = re.sub(r"\s+", " ", seg.text_en).strip().lower()
        if needle and needle not in normalized_blob:
            return False
    return len(manifest) > 0


def inject_kr_into_04(en_content: str, kr_paragraphs: list[str]) -> str:
    lines = en_content.splitlines()
    out: list[str] = []
    kr_idx = 0
    for line in lines:
        if line.strip().upper().startswith("KR:") and kr_idx < len(kr_paragraphs):
            out.append(f"KR: {kr_paragraphs[kr_idx]}")
            kr_idx += 1
        else:
            out.append(line)
    return "\n".join(out) + "\n"


def generate_meta(meta: VideoMeta, level: int) -> str:
    return (
        f"title: {meta.title}\n"
        f"level: Level {level}\n"
        f"source: YouTube\n"
        f"video_url: {meta.video_url}\n"
        f"video_id: {meta.video_id}\n"
        f"channel: {meta.channel or '-'}\n"
        f"notes: auto-generated by listening automation v1\n"
    )


def _transcript_text(segments: list[Segment]) -> str:
    return " ".join(s.text_en for s in segments)


def _all_sentences(segments: list[Segment]) -> list[str]:
    sents: list[str] = []
    for seg in segments:
        sents.extend(split_sentences(seg.text_en))
    return sents


def _few_shot(name: str, max_lines: int = 35) -> str:
    path = FEW_SHOT_DIR / name
    if not path.exists():
        return ""
    return "\n".join(path.read_text(encoding="utf-8").splitlines()[:max_lines])


def _translate(en: str, *, allow_placeholder: bool = False) -> str:
    if vertex_configured():
        try:
            return translate_literal_kr(en)
        except Exception as exc:
            if not allow_placeholder:
                raise RuntimeError(f"BLOCKED: literal KR translation failed: {exc}") from exc
    if openai_configured():
        try:
            return _openai_literal(en)
        except Exception as exc:
            if not allow_placeholder:
                raise RuntimeError(f"BLOCKED: OpenAI fallback failed: {exc}") from exc
    if allow_placeholder:
        return f"[KR translation pending: {en[:60]}...]"
    raise RuntimeError("BLOCKED: Vertex AI (ADC) required for literal KR translation")


def _translate_batch(
    items: list[tuple[str, str]],
    *,
    allow_placeholder: bool = False,
) -> dict[str, str]:
    if not items:
        return {}
    if allow_placeholder:
        return {item_id: f"[KR translation pending: {text[:60]}...]" for item_id, text in items}
    if vertex_configured():
        try:
            return translate_literal_kr_batch(items)
        except Exception as exc:
            try:
                return {item_id: translate_literal_kr(text) for item_id, text in items}
            except Exception:
                raise RuntimeError(f"BLOCKED: batch literal KR translation failed: {exc}") from exc
    if openai_configured():
        return {item_id: _openai_literal(text) for item_id, text in items}
    raise RuntimeError("BLOCKED: Vertex AI (ADC) required for batch literal KR translation")


def _level_guidance(level: int) -> str:
    return LEVEL_GENERATION_GUIDANCE.get(level, LEVEL_GENERATION_GUIDANCE[2])


def generate_intro_from_transcript(
    segments: list[Segment],
    level: int,
    *,
    allow_placeholder: bool = False,
) -> str:
    transcript = _transcript_text(segments)
    level_hint = _level_guidance(level)
    if vertex_configured() and not allow_placeholder:
        example = _few_shot("01_intro.txt", 5)
        data = generate_json(
            f"""Create one intro for a Level {level} English listening lesson page.
{level_hint}
Example:
{example}

Write one EN intro sentence (1-2 sentences) summarizing the story for learners.
Use content from this transcript only. Return JSON: {{"intro_en": "..."}}

Transcript excerpt:
{transcript[:8000]}
"""
        )
        en = str(data.get("intro_en", "")).strip()
    else:
        sents = _all_sentences(segments)
        en = sents[0] if sents else transcript[:200]

    kr = _translate(en, allow_placeholder=allow_placeholder)
    return f"EN: {en}\nKR: {kr}\n"


def build_sections_for_transcript(
    segments: list[Segment],
    video_id: str,
    level: int,
    *,
    allow_placeholder: bool = False,
    chapters: list[dict] | None = None,
) -> list[StorySection]:
    sections = build_story_sections(
        segments,
        video_id,
        allow_placeholder=allow_placeholder,
        chapters=chapters,
    )
    fill_section_content(sections, segments, level=level, allow_placeholder=allow_placeholder)
    return sections


def generate_core_from_sections(
    sections: list[StorySection],
    *,
    allow_placeholder: bool = False,
) -> str:
    return render_core_file(sections, _translate_batch, allow_placeholder=allow_placeholder)


def generate_summary_from_sections(
    sections: list[StorySection],
    *,
    allow_placeholder: bool = False,
) -> str:
    return render_summary_file(sections, _translate_batch, allow_placeholder=allow_placeholder)


def _level_wordcard_sample(level: int, max_lines: int = 45) -> str:
    level_dir = LISTENING_ROOT / level_folder(level)
    if level_dir.is_dir():
        for folder in sorted(level_dir.iterdir()):
            wc = folder / "05_wordcard.txt"
            if wc.is_file():
                return "\n".join(wc.read_text(encoding="utf-8").splitlines()[:max_lines])
    return _few_shot("05_wordcard.txt", max_lines)


_NON_GERUND_ING = frozenset(
    {
        "building",
        "ceiling",
        "during",
        "evening",
        "feeling",
        "morning",
        "nothing",
        "something",
        "spring",
        "string",
        "thing",
    }
)


def _lemma_level1_headword(headword: str, part_of_speech: str) -> str:
    """Normalize -ing gerunds/participles to base verb lemma for Level 1 headwords."""
    word = headword.strip()
    lw = word.lower()
    if lw in _NON_GERUND_ING or len(lw) <= 4 or not lw.endswith("ing"):
        return word
    stem = lw[:-3]
    if len(stem) < 2:
        return word
    pos = part_of_speech.lower()
    if len(stem) >= 2 and stem[-1] == stem[-2] and stem[-1] not in "aeiou":
        lemma = stem[:-1]
    elif stem[-1] in "tvklgp" and not stem.endswith("e"):
        lemma = stem + "e"
    else:
        lemma = stem
    if pos.startswith("verb") or "participle" in pos or "gerund" in pos or pos == "noun":
        return lemma if word.islower() else lemma.capitalize()
    return word


def generate_wordcards_from_transcript(
    segments: list[Segment],
    core_text: str,
    level: int,
    *,
    allow_placeholder: bool = False,
) -> str:
    transcript = _transcript_text(segments)
    level_hint = _level_guidance(level)
    lemma_rule = ""
    if level == 1:
        lemma_rule = (
            "- Level 1 headword must use dictionary base/lemma form, NOT -ing gerund/participle forms "
            "(e.g. farming→farm, writing→write). Show the actual -ing form in example_en when needed.\n"
        )
    if vertex_configured() and not allow_placeholder:
        example = _level_wordcard_sample(level)
        data = generate_json(
            f"""Create vocabulary word cards for Level {level} English listening learners.
{level_hint}
Rules:
- Pick a natural count (typically around 10; range {WORDCARD_MIN}-{WORDCARD_MAX}) based on learning value, NOT a fixed number
- Priority: context importance > level fit > learning value
- Include words critical to understanding the video; do NOT pad with easy/common words
- Do NOT drop important words to hit a count
- Skip overly common function words, trivial words, words chosen only for length or early appearance
- Proper nouns only when essential for comprehension
- Return English fields only (Korean will be added separately)
- meaning_kr will be generated to MATCH part_of_speech (verb gloss must be a Korean verb)
{lemma_rule}
Return JSON: {{"cards": [{{"headword": "...", "part_of_speech": "...", "definition_en": "...", "example_en": "..."}}]}}

Reference Level {level} vocabulary style:
{example}

Transcript excerpt:
{transcript[:10000]}

Core sentences excerpt:
{core_text[:3000]}
"""
        )
        cards = data.get("cards", []) if isinstance(data, dict) else data
        if not isinstance(cards, list):
            raise RuntimeError("BLOCKED: Word card generation returned invalid format")
        if len(cards) < WORDCARD_MIN or len(cards) > WORDCARD_MAX:
            raise RuntimeError(
                f"BLOCKED: Word card generation returned {len(cards)} cards "
                f"(expected {WORDCARD_MIN}-{WORDCARD_MAX} based on content value)"
            )
        if level == 1:
            for card in cards:
                hw = str(card.get("headword", "")).strip()
                pos = str(card.get("part_of_speech", "")).strip()
                if hw:
                    card["headword"] = _lemma_level1_headword(hw, pos)
    else:
        cards = _heuristic_wordcards(core_text)

    return _format_wordcards(cards, allow_placeholder=allow_placeholder)


def _format_wordcards(cards: list[dict[str, Any]], *, allow_placeholder: bool) -> str:
    from automation.listening.vertex_client import meaning_matches_pos, translate_wordcard_meanings

    batch_items: list[tuple[str, str]] = []
    meaning_items: list[dict[str, str]] = []
    structured: list[dict[str, str]] = []
    for i, card in enumerate(cards, start=1):
        hw = str(card.get("headword", "word")).strip()
        pos = str(card.get("part_of_speech", "noun")).strip()
        def_en = str(card.get("definition_en", f"definition of {hw}")).strip()
        ex_en = str(card.get("example_en", f"This story mentions {hw}.")).strip()
        structured.append({"hw": hw, "pos": pos, "def_en": def_en, "ex_en": ex_en})
        meaning_items.append(
            {
                "id": f"c{i}_m",
                "headword": hw,
                "part_of_speech": pos,
                "definition_en": def_en,
                "example_en": ex_en,
            }
        )
        batch_items.append((f"c{i}_d", def_en))
        batch_items.append((f"c{i}_e", ex_en))

    kr_map = _translate_batch(batch_items, allow_placeholder=allow_placeholder)
    if allow_placeholder or not vertex_configured():
        meaning_map = {
            str(item["id"]): f"[KR pending: {item['headword']}]" for item in meaning_items
        }
        if not allow_placeholder and meaning_items:
            raise RuntimeError("BLOCKED: Vertex AI required for wordcard meanings")
    else:
        meaning_map = translate_wordcard_meanings(meaning_items)

    lines: list[str] = []
    for i, card in enumerate(structured, start=1):
        meaning_kr = meaning_map[f"c{i}_m"]
        if not allow_placeholder and not meaning_matches_pos(meaning_kr, card["pos"]):
            raise RuntimeError(
                f"BLOCKED: wordcard POS mismatch for {card['hw']} ({card['pos']}): {meaning_kr}"
            )
        conflict = meaning_conflicts_with_context(
            card["hw"], meaning_kr, card["def_en"], card["ex_en"]
        )
        if not allow_placeholder and conflict:
            raise RuntimeError(f"BLOCKED: wordcard sense mismatch for {card['hw']}: {conflict}")
        lines.append(f"[Card {i}]")
        lines.append(f"headword: {card['hw']}")
        lines.append(f"part_of_speech: {card['pos']}")
        lines.append(f"meaning_kr: {meaning_kr}")
        lines.append(f"definition_en: {card['def_en']}")
        lines.append(f"definition_kr_literal: {kr_map[f'c{i}_d']}")
        lines.append(f"example_en: {card['ex_en']}")
        lines.append(f"example_kr_literal: {kr_map[f'c{i}_e']}")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def translate_paragraphs_kr(paragraphs: list[str], *, allow_placeholder: bool = False) -> list[str]:
    """Translate each English sentence, then rejoin so KR units match EN sentence order."""
    if not paragraphs:
        return []
    if allow_placeholder:
        return [f"[KR translation pending: {p[:60]}...]" for p in paragraphs]

    items: list[tuple[str, str]] = []
    structure: list[list[str]] = []
    for i, para in enumerate(paragraphs, start=1):
        sents = [s.strip() for s in split_sentences(para) if s.strip()]
        if not sents:
            sents = [para.strip()] if para.strip() else [""]
        ids: list[str] = []
        for j, sent in enumerate(sents, start=1):
            sid = f"p{i}s{j}"
            items.append((sid, sent))
            ids.append(sid)
        structure.append(ids)

    kr_map = _translate_batch(items, allow_placeholder=allow_placeholder)
    assembled: list[str] = []
    for ids in structure:
        units: list[str] = []
        for sid in ids:
            unit = (kr_map.get(sid) or "").strip()
            unit = re.sub(r"[.!?]+", "", unit).strip()
            unit = re.sub(r"\s+", " ", unit)
            if unit:
                units.append(unit + ".")
        assembled.append(" ".join(units) if units else "")
    return assembled


def _translate_with_instruction(en: str, instruction: str, *, allow_placeholder: bool = False) -> str:
    if vertex_configured():
        try:
            from automation.listening.vertex_client import generate_text

            return generate_text(f"{instruction}\n\nEnglish:\n{en}")
        except Exception as exc:
            if not allow_placeholder:
                raise RuntimeError(f"BLOCKED: 04 KR literal translation failed: {exc}") from exc
    if openai_configured():
        try:
            return _openai_literal(en, instruction)
        except Exception as exc:
            if not allow_placeholder:
                raise RuntimeError(f"BLOCKED: OpenAI fallback failed: {exc}") from exc
    if allow_placeholder:
        return f"[KR translation pending: {en[:60]}...]"
    raise RuntimeError("BLOCKED: Vertex AI (ADC) required for 04 KR translation")


def _heuristic_wordcards(core_text: str) -> list[dict[str, Any]]:
    words = re.findall(r"\b[A-Za-z]{5,}\b", core_text)
    unique: list[str] = []
    skip = {"about", "there", "their", "which", "would", "could", "should", "every", "after"}
    for w in words:
        lw = w.lower()
        if lw in skip:
            continue
        if lw not in unique:
            unique.append(lw)
        if len(unique) >= 8:
            break
    if not unique:
        unique = ["lesson", "story"]
    return [
        {
            "headword": w,
            "part_of_speech": "noun",
            "definition_en": f"common English definition of {w}",
            "example_en": f"This story mentions {w} in an important moment.",
        }
        for w in unique
    ]


def _openai_literal(en: str, instruction: str | None = None) -> str:
    if not allow_openai_fallback():
        raise RuntimeError("BLOCKED: OpenAI fallback not allowed (set ALLOW_OPENAI_FALLBACK=1)")
    from openai import OpenAI

    prompt = instruction or LITERAL_KR_INSTRUCTION
    client = OpenAI()
    resp = client.chat.completions.create(
        model=os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        messages=[{"role": "user", "content": f"{prompt}\n\nEnglish:\n{en}"}],
    )
    return (resp.choices[0].message.content or "").strip()


def _count_blocks(content: str, label: str) -> int:
    return len(re.findall(rf"\[{re.escape(label)}\s+\d+\]", content))


def _verified_script_text(segments: list[Segment] | None, content_04: str) -> str:
    if segments:
        return " ".join(s.text_en for s in segments)
    en_lines = [
        line.split(":", 1)[1].strip()
        for line in content_04.splitlines()
        if line.strip().upper().startswith("EN:")
    ]
    return " ".join(en_lines)


def _validate_wordcards(content: str) -> tuple[bool, str]:
    blocks = re.split(r"\[Card\s+\d+\]", content)
    card_blocks = [b for b in blocks if b.strip()]
    if len(card_blocks) < WORDCARD_MIN:
        return False, f"05_wordcard.txt has {len(card_blocks)} cards, need at least {WORDCARD_MIN}"
    if len(card_blocks) > WORDCARD_MAX:
        return False, f"05_wordcard.txt has {len(card_blocks)} cards, exceeds {WORDCARD_MAX}"
    for i, block in enumerate(card_blocks, start=1):
        for field in WORDCARD_FIELDS:
            if field not in block:
                return False, f"05_wordcard.txt Card {i} missing {field.rstrip(':')}"
        pos_m = re.search(r"part_of_speech:\s*(.+)", block)
        kr_m = re.search(r"meaning_kr:\s*(.+)", block)
        if pos_m and kr_m:
            from automation.listening.vertex_client import meaning_matches_pos

            pos = pos_m.group(1).strip()
            kr = kr_m.group(1).strip()
            if kr and not kr.startswith("[KR") and not meaning_matches_pos(kr, pos):
                return False, f"05_wordcard.txt Card {i} POS mismatch ({pos}): {kr}"
        hw_m = re.search(r"headword:\s*(.+)", block)
        def_m = re.search(r"definition_en:\s*(.+)", block)
        ex_m = re.search(r"example_en:\s*(.+)", block)
        if hw_m and kr_m and def_m and ex_m:
            kr = kr_m.group(1).strip()
            if kr and not kr.startswith("[KR"):
                conflict = meaning_conflicts_with_context(
                    hw_m.group(1).strip(),
                    kr,
                    def_m.group(1).strip(),
                    ex_m.group(1).strip(),
                )
                if conflict:
                    return False, f"05_wordcard.txt Card {i} sense mismatch: {conflict}"
    return True, "OK"


def count_en_punctuation(content_04: str) -> dict[str, int]:
    en = " ".join(
        line.split(":", 1)[1]
        for line in content_04.splitlines()
        if line.strip().upper().startswith("EN:")
    )
    return {ch: en.count(ch) for ch in ". ,?!:;".replace(" ", "")}


def _04_paragraph_pairs(content_04: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    en = ""
    kr = ""
    for line in content_04.splitlines():
        stripped = line.strip()
        if stripped.upper().startswith("EN:"):
            en = stripped.split(":", 1)[1].strip()
        elif stripped.upper().startswith("KR:"):
            kr = stripped.split(":", 1)[1].strip()
            if en:
                pairs.append((en, kr))
            en = ""
            kr = ""
    return pairs


def validate_04_en_punctuation(content_04: str) -> tuple[bool, str]:
    en = " ".join(en for en, _kr in _04_paragraph_pairs(content_04))
    sentences = [s for s in split_sentences(en) if s.strip()]
    counts = count_en_punctuation(content_04)
    if len(sentences) >= 40 and counts.get(",", 0) == 0:
        return False, "04 EN punctuation flattened to periods only (comma count 0)"
    return True, "OK"


def count_04_kr_sentence_alignment_mismatches(content_04: str) -> tuple[int, str]:
    mismatches = 0
    sample = ""
    for idx, (en, kr) in enumerate(_04_paragraph_pairs(content_04), start=1):
        if not kr or kr.startswith("[KR"):
            continue
        en_n = len([s for s in split_sentences(en) if s.strip()])
        kr_n = len([s for s in split_sentences(kr) if s.strip()])
        if en_n and kr_n and en_n != kr_n:
            mismatches += 1
            if not sample:
                sample = f"Paragraph {idx}: EN {en_n} vs KR {kr_n}"
    return mismatches, sample


def validate_04_kr_sentence_alignment(content_04: str) -> tuple[bool, str]:
    mismatches, sample = count_04_kr_sentence_alignment_mismatches(content_04)
    if mismatches:
        return False, f"04 KR sentence alignment mismatch ({mismatches}): {sample}"
    return True, "OK"


def validate_format_files(
    files: dict[str, str],
    *,
    segments: list[Segment] | None = None,
    reject_placeholders: bool = True,
) -> tuple[bool, str]:
    required = {
        "00_meta.txt": ["title:", "level:"],
        "01_intro.txt": ["EN:", "KR:"],
        "02_core.txt": ["[Sentence"],
        "03_summary.txt": ["[Part"],
        "04_full_script.txt": ["[Paragraph", "EN:"],
        "05_wordcard.txt": ["[Card"],
    }
    for name, markers in required.items():
        content = files.get(name, "")
        for m in markers:
            if m not in content:
                return False, f"{name} missing {m}"
        if reject_placeholders and "[KR translation pending:" in content:
            return False, f"{name} contains untranslated placeholder KR"

    core_n = _count_blocks(files.get("02_core.txt", ""), "Sentence")
    sum_n = _count_blocks(files.get("03_summary.txt", ""), "Part")
    if core_n != sum_n:
        return False, f"02_core.txt has {core_n} sentences but 03_summary.txt has {sum_n} parts (section mismatch)"
    if core_n < 1:
        return False, "02_core.txt has no sentences (need at least 1 section)"

    verified = _verified_script_text(segments, files.get("04_full_script.txt", ""))
    verified_keys = {
        re.sub(r"\s+", " ", s.strip())
        for s in split_sentences(verified)
        if s.strip()
    }
    for sent in extract_core_sentences(files.get("02_core.txt", "")):
        key = re.sub(r"\s+", " ", sent.strip())
        if key not in verified_keys:
            return False, f"02_core.txt sentence is not an exact Full Script sentence: {sent[:80]}"
        if not is_complete_sentence(sent):
            return False, f"02_core.txt core is not a complete sentence: {sent[:80]}"

    ok, reason = _validate_wordcards(files.get("05_wordcard.txt", ""))
    if not ok:
        return False, reason

    if reject_placeholders:
        ok, reason = validate_04_en_punctuation(files.get("04_full_script.txt", ""))
        if not ok:
            return False, reason
        ok, reason = validate_04_kr_sentence_alignment(files.get("04_full_script.txt", ""))
        if not ok:
            return False, reason

    return True, "OK"
